name: build adocs

on:
  push:
    branches:
    - main
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  adoc_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.12
    - name: Install MkDocs
      run: pip install mkdocs
    - name: Install plugins
      run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin
    - name: Get build container
      id: adocbuild
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor -b docbook -a leveloffset=+1 -o docbook.xml master.adoc"
    - name: Create docs dir
      uses: docker://alpine:3.19
      with:
        args: "mkdir -vp docs"
    - name: Convert to Markdown
      uses: docker://pandoc/core:2.9
      with:
        args: "--atx-headers --wrap=preserve -t markdown_strict -f docbook -o docs/index.md docbook.xml"
    - name: Print execution time
      run: echo "Time ${{ steps.adocbuild.outputs.time }}"
    - name: Copy images
      run: cp -r images docs/images
    - name: Build site
      run: mkdocs build
    - name: Configure Pages
      uses: actions/configure-pages@v4.0.0
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3.0.0
      with:
        path: ./site
    - name: Deploy to Pages
      uses: actions/deploy-pages@v4.0.3
