name: build adocs

on:
  push:
    branches:
    - main
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  adoc_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get build container
      id: adocbuild
      uses: avattathil/asciidoctor-action@153b34f78be19907024c3dfb128874a36cec2535
      with:
          program: "asciidoctor -b docbook -a leveloffset=+1 -o docbook.xml master.adoc"
    - name: Print execution time
      run: echo "Time ${{ steps.adocbuild.outputs.time }}"
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: docbook.xml
        path: ./docbook.xml
  convert_md:
    runs-on: ubuntu-latest
    needs:
    - adoc_build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: docbook.xml
        path: .
    - name: Convert to Markdown
      uses: docker://pandoc/core:2.9
      with:
        args: "--atx-headers --wrap=preserve -t markdown_strict -f docbook -o index.md docbook.xml"
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: index.md
        path: ./index.md
  build:
    runs-on: ubuntu-latest
    needs:
    - convert_md
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Create docs dir
      run: mkdir docs
    - name: Copy images
      run: cp -r images docs/images
    - name: Download artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: index.md
        path: ./docs
    - name: Build site
      uses: romw314/mkdocs-action@v8
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3.0.0
  deploy:
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
    - name: Configure Pages
      uses: actions/configure-pages@v3.0.6
    - name: Deploy to Pages
      uses: actions/deploy-pages@v3.0.1
